// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwrvltgouwpukhorjykx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3cnZsdGdvdXdwdWtob3JqeWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTU3MDAsImV4cCI6MjA2NjI3MTcwMH0.Se7-hrOpuSTMLqFd8iQkt0kSxG4PTPJRCkeUHzHa5Js";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});